# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.yaml', '.'),
        ('cache.json', '.') if os.path.exists('cache.json') else None,
    ],
    hiddenimports=[
        # Dynamic parser modules
        'parsers.summary_hearing_docs_pdf',
        'parsers.summary_committee_docx',
        'parsers.summary_committee_pdf',
        'parsers.summary_bill_tab_text',
        'parsers.summary_hearing_pdf',
        'parsers.votes_bill_embedded',
        'parsers.votes_hearing_committee',
        'parsers.votes_committee_documents',
        'parsers.votes_docx',
        'parsers.votes_bill_pdf',
        
        # Third-party library hidden imports
        'bs4.builder._lxml',
        'bs4.builder._html5lib',
        'lxml.etree',
        'lxml.html',
        'PyPDF2._codecs',
        'PyPDF2.generic',
        'PIL._imaging',
        'PIL.Image',
        'docx.oxml',
        'docx.oxml.ns',
        'yaml.constructor',
        'yaml.loader',
        
        # Standard library modules that might be missed
        'tkinter',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'webbrowser',
        'importlib',
        'json',
        'logging',
        'datetime',
        'pathlib',
        'urllib.parse',
        're',
        'requests',
        'requests.sessions',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.exceptions',
        'requests.models',
        'requests.packages',
        'requests.sessions',
        'requests.utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)